version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8080"
    environment:
      - JWT_SECRET_KEY=mysecretkey
  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
